services:
  # 独立部署的邮件发送微服务
  email-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: email-message-service
    restart: on-failure
    env_file:
      - .env
    volumes:
      - ./config.yaml:/app/config.yaml:ro
    networks:
      - go-net

networks:
  go-net:
    name: go-net
    external: true
